// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8lJR0QoL-iGxaBY3oHSH_1rVtO09W6k',
    appId: '1:323288641025:web:e80ccc2f439396ae21da00',
    messagingSenderId: '323288641025',
    projectId: 'olek-udemy-portfolio',
    authDomain: 'olek-udemy-portfolio.firebaseapp.com',
    storageBucket: 'olek-udemy-portfolio.firebasestorage.app',
    measurementId: 'G-LZWVWH992K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIv7--bTrZocaESj0r-xsUI-2HJycIfU4',
    appId: '1:323288641025:android:54fd0c0d713f731521da00',
    messagingSenderId: '323288641025',
    projectId: 'olek-udemy-portfolio',
    storageBucket: 'olek-udemy-portfolio.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYwDIRAv_s4ju5Y8LRkyOXZKvsPAgCeyo',
    appId: '1:323288641025:ios:407214ae348cd21121da00',
    messagingSenderId: '323288641025',
    projectId: 'olek-udemy-portfolio',
    storageBucket: 'olek-udemy-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.olekUdemyPortfolio',
  );
}
